name: PR CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-synth:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.CDK_DEFAULT_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Install Lambda function dependencies
        run: |
          cd src/functions/reminder
          npm ci
          cd ../../..

      - name: Run infrastructure tests
        run: npm run test:ci
        env:
          RECEPIENT_PHONE_NUMBER: ${{ secrets.RECEPIENT_PHONE_NUMBER }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}

      - name: Run Lambda function tests
        run: |
          cd src/functions/reminder
          npm test
          cd ../../..

      - name: Synthesize CDK app
        run: npm run cdk synth
        env:
          RECEPIENT_PHONE_NUMBER: ${{ secrets.RECEPIENT_PHONE_NUMBER }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results/
            src/functions/reminder/junit.xml
            src/functions/reminder/coverage/
